# fly.toml app configuration file generated for node-portfolio on 2023-07-21T21:06:59+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "node-portfolio"
primary_region = "waw"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[env]
  MYSQL_HOST="portfolio-mysql-db.internal"
  MYSQL_DATABASE = "portfolio-mysql"